name: custom_runner

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testing:
    #runs-on: ubuntu-latest
    #runs-on: self-hosted
    runs-on: linux-pc

    steps:
    # - name: dir
    - uses: actions/checkout@v2
    - run: echo $PWD
    - name: codestyle
       run: |
        cd include
        docker build -t codestyle .
    - name: tests
      run: |
        cp -r ./include ./docker_test/include
        cp -r ./src ./docker_test/src
        cd docker_test
        docker build -t tests .
        cd ..
        
  build: 
    needs: testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: docker build -t 1205200012052000/hse_devops_deanery:ver_$GITHUB_RUN_NUMBER .
    - name: run
      run: docker run -v $PWD/input_data:/input_data --name mounted 1205200012052000/hse_devops_deanery:ver_$GITHUB_RUN_NUMBER 
    - name: upload
      run: |
        docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
        docker push 1205200012052000/hse_devops_deanery:ver_$GITHUB_RUN_NUMBER
  
  download_artifacts:
    needs: build
    runs-on: potato
    steps:
      - uses: actions/checkout@v2
      - name: local_docker
        run: |
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
          docker pull 1205200012052000/hse_devops_deanery:ver_$GITHUB_RUN_NUMBER
          docker run -v /home/ubuntu/actions-runner/work_dir/dev-ops/dev-ops/input_data:/input_data --name mounted_$GITHUB_RUN_NUMBER 1205200012052000/hse_devops_deanery:ver_$GITHUB_RUN_NUMBER > artifact_output.txt
      - name: artifacts
        uses: actions/upload-artifact@v1
        with:  
          name: result
          path: artifact_output.txt