name: custom_runner

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    #runs-on: ubuntu-latest'
    runs-on: self-hosted

    steps:
    # - name: dir
    - uses: actions/checkout@v2
    # - run: echo $PWD
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install dependencies for code stype check
      run: |
        python -m pip install --upgrade pip
        pip install cpplint
    - name: code style check
      run: |
        cpplint --verbose=2 include/Deanery.h
        cpplint --verbose=2 include/Group.h
        cpplint --verbose=2 include/Student.h
        cpplint --verbose=2 src/Deanery.cpp
        cpplint --verbose=2 src/Group.cpp
        cpplint --verbose=2 src/Student.cpp
        cpplint --verbose=2 src/main.cpp
    - name: tests
      run: |
        cp -r ./include ./docker_test/include
        cp -r ./src ./docker_test/src
        cd docker_test
        docker build -t tests .
        cd ..
    - name: build
      run: docker build -t 1205200012052000/hse_devops_deanery:ver_$GITHUB_RUN_NUMBER .
    - name: run
      run: docker run -v /home/runner/work/devops-18pi-NoVarlok/devops-18pi-NoVarlok/input_data:/input_data --name mounted 1205200012052000/hse_devops_deanery:ver_$GITHUB_RUN_NUMBER 
    - name: upload
      run: |
        docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
        docker push 1205200012052000/hse_devops_deanery:ver_$GITHUB_RUN_NUMBER
